### ISSUE TITLE
DTD Validation XML Examples

### ISSUE THREAD

**Issue by Ordinateur-Hack** [StudentsAgainstCovid19/corona-aid-api#104] opened 2020-07-04 14:49 UTC
I need XML-examples for the following endpoints and tags:

Infected
- lastUnsuccessfulCallTodayString

Realtime (SSE)
- lastUnsuccessfulCallTodayString

**Comment by marcauberer** [comment] 2020-07-04 14:58
Here an xml example for both of the cases:
```xml
<item>
   <lastUnsuccessfulCallTodayString>16:52</lastUnsuccessfulCallTodayString>
   <id>372</id>
   <age>76</age>
   <forename>Buket</forename>
   <surname>Salman</surname>
   <lat>49.0134879</lat>
   <lon>8.443705614254306</lon>
   <phone>0721 58248033</phone>
   <done>false</done>
   <locked>false</locked>
   <lastUnsuccessfulCallToday>1593874361727</lastUnsuccessfulCallToday>
   <personalFeeling>1</personalFeeling>
   <sumInitialDiseases>0</sumInitialDiseases>
   <sumSymptoms>5</sumSymptoms>
</item>
```

**Comment by Ordinateur-Hack** [comment] 2020-07-04 15:04
Great, I'd also appreciate some examples for the following tags:

Infected/ID
- initialDiseases
- notes

Realtime
- lastcall

**Comment by marcauberer** [comment] 2020-07-04 15:14
Infected/ID:
- Notes is a simple string, which also can be `null`
- initialDiseases: @jatsqi has to do the pending task to create test data for initial diseases, but I just created a test record for you. You can find it [here](https://api.corona-aid-ka.de/infected/1)

Realtime:
- I assume, that you mean the `called` attribute?! This is a boolean

**Comment by Ordinateur-Hack** [comment] 2020-07-04 15:28
Thanks @marcauberer. I didn't realize that I wasn't looking at the original XML sent via the realtime endpoint, but instead at a file that @keksklauer4 constructed via JS. Could you provide an XML example for the realtime endpoint?

**Comment by marcauberer** [comment] 2020-07-04 15:35
Sure, but I have to construct it manually (please mind, that it could contain mistakes).
```xml
<InfectedRealtimeDto>
   <infectedId>1<infectedId>
   <done>true</done>
   <called>true</called>
   <lastUnsuccessfulCallTodayString>14:00</lastUnsuccessfulCallTodayString>
   <locked>false</locked>
</InfectedRealtimeDto>
```

**Comment by Ordinateur-Hack** [comment] 2020-07-04 15:37
@marcauberer Is there a way you can guarantee that the tags are correct? There must be since we've defined the tags on our own ;)

**Comment by Ordinateur-Hack** [comment] 2020-07-04 15:40
Or did you just refer to the XML syntax itself when you wrote 

> could contain mistakes

**Comment by marcauberer** [comment] 2020-07-04 15:43
The problem is, that this is not an actual xml file. This is a permanent open text stream. I don't know how the xml validation would take place. You can ask @jatsqi for more information cause he's the one, who developed the realtime endpoint.

**Comment by jatsqi** [comment] 2020-07-04 18:59
In general the xml you sent is correct. @marcauberer 
But atm the surrounding xml tag can vary, because the response is never a single item, it is **always** a set of some other collection type. That is also the reason why the tag is not fixed (different collection type -> different tag).
I will fix this in my next PR.

**Comment by marcauberer** [comment] 2020-07-07 12:09
We decided to not realize xml validation for the realtime endpoint, so we can close this for now

**Closed by marcauberer** 2020-07-07 12:09 UTC
Labels: help wanted
